### ISSUE TITLE
Your openai API key is visible

### ISSUE THREAD

**Issue by joshnielsen876** [mmilunovic-mdcs/prompt-breeder#1]
Check your .env file, anyone could see and use your api key. Unless its a dummy one, of course. Are you planning to do additional maintenance with this project? I'm interested in it, but I want to use the open source models instead of openAI.

**Comment by mmilunovic-mdcs** [comment]
Thanks for noticing this!

> Are you planning to do additional maintenance with this project?

Not really, it was just a demonstration of a paper I read. 😄

**Comment by joshnielsen876** [comment]
Happy to help! It's a fascinating paper, I was surprised to see implementations like yours out so soon after it was published! Well done!
